### ISSUE TITLE
No icons folder?

### ISSUE THREAD

**Issue by tylerhyperHD** [connor4312/multicraft#10]
Well it's self-explanatory, there is no /static/icons/ folder.

**Comment by ItzLevvie** [comment]
Multicraft 2.0.0 is currently in Beta. However, there is no ETA at this stage.

For more information, contact multicraft@xhost.ch

Thanks,

R Sajeey

**Comment by connor4312** [comment]
The Multicraft 2 preview is out, please use that http://multicraft.org/site/page?view=news
