### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by Tyguh** [connor4312/multicraft#11]
I want to use [Sourcegraph](https://sourcegraph.com) for multicraft code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/connor4312/multicraft. (It should only take 30 seconds.)

Thank you!

**Comment by connor4312** [comment]
![](http://peet.io/i/15-04-JxO3vpNX04iE3P38fWmM1joOi.png)
