### ISSUE TITLE
API

### ISSUE THREAD

**Issue by ghost** [connor4312/multicraft#6]
Hey,

Whenever I click on "Generate API Key", nothing will happen and it will just add # to the link at the top.

Please Help,

Thanks, 

Aden D.

**Comment by cameroncoats** [comment]
Are you able to release a snippet of the affected views? I've tried to fix this myself but honestly haven't got anywhere; I can't find a single reason that it shouldn't work.
If you could point me in the right direction I'll be more than happy to submit a PR if I find a fix.
Thanks,
Cam

**Comment by connor4312** [comment]
Multicraft 2 is in the late stages of pre-release. Should be out soon anyhow, just wait a bit.

**Comment by cameroncoats** [comment]
No worries, do you have a rough ETA?

**Comment by dragonaden** [comment]
Same, ^

**Comment by connor4312** [comment]
I'm no longer working with them, so unfortunately I have no confirmed time nor official information.
